spring.application.name=Helpdesk

# Conexao via Public Access do Railway
spring.datasource.url=jdbc:mysql://altaria.proxy.rlwy.net:29472/railway?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=DTN1VGs1GHDupDiqWQdOEDHHlOTfkYJo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracoes do JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Suporte a Enums
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.mvc.format.enum-case-sensitive=false
