spring.application.name=Helpdesk

# Configuração do Banco de Dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/att_helpD
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Suporte a Enums sem diferenciação de maiúsculas/minúsculas
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.mvc.format.enum-case-sensitive=false